-- OMNILIFE x SEYTU - rutas de imágenes seguras 01..60
-- Ejecutar en phpMyAdmin sobre la base omnilife_seytu.
USE `omnilife_seytu`;

UPDATE `productos` SET `imagen`='assets/IMG/imagen-01.png' WHERE `id_producto`=1;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-02.png' WHERE `id_producto`=2;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-03.png' WHERE `id_producto`=3;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-04.png' WHERE `id_producto`=4;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-05.png' WHERE `id_producto`=5;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-06.png' WHERE `id_producto`=6;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-07.png' WHERE `id_producto`=7;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-08.png' WHERE `id_producto`=8;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-09.png' WHERE `id_producto`=9;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-10.png' WHERE `id_producto`=10;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-11.png' WHERE `id_producto`=11;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-12.png' WHERE `id_producto`=12;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-13.png' WHERE `id_producto`=13;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-14.png' WHERE `id_producto`=14;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-15.png' WHERE `id_producto`=15;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-16.png' WHERE `id_producto`=16;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-17.png' WHERE `id_producto`=17;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-18.png' WHERE `id_producto`=18;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-19.png' WHERE `id_producto`=19;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-20.png' WHERE `id_producto`=20;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-21.png' WHERE `id_producto`=21;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-22.png' WHERE `id_producto`=22;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-23.png' WHERE `id_producto`=23;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-24.png' WHERE `id_producto`=24;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-25.png' WHERE `id_producto`=25;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-26.png' WHERE `id_producto`=26;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-27.png' WHERE `id_producto`=27;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-28.png' WHERE `id_producto`=28;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-29.png' WHERE `id_producto`=29;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-30.png' WHERE `id_producto`=30;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-31.png' WHERE `id_producto`=31;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-32.png' WHERE `id_producto`=32;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-33.png' WHERE `id_producto`=33;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-34.png' WHERE `id_producto`=34;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-35.png' WHERE `id_producto`=35;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-36.png' WHERE `id_producto`=36;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-37.png' WHERE `id_producto`=37;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-38.png' WHERE `id_producto`=38;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-39.png' WHERE `id_producto`=39;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-40.png' WHERE `id_producto`=40;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-41.png' WHERE `id_producto`=41;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-42.png' WHERE `id_producto`=42;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-43.png' WHERE `id_producto`=43;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-44.png' WHERE `id_producto`=44;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-45.png' WHERE `id_producto`=45;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-46.png' WHERE `id_producto`=46;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-47.png' WHERE `id_producto`=47;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-48.png' WHERE `id_producto`=48;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-49.png' WHERE `id_producto`=49;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-50.png' WHERE `id_producto`=50;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-51.png' WHERE `id_producto`=51;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-52.png' WHERE `id_producto`=52;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-53.png' WHERE `id_producto`=53;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-54.png' WHERE `id_producto`=54;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-55.png' WHERE `id_producto`=55;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-56.png' WHERE `id_producto`=56;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-57.png' WHERE `id_producto`=57;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-58.png' WHERE `id_producto`=58;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-59.png' WHERE `id_producto`=59;
UPDATE `productos` SET `imagen`='assets/IMG/imagen-60.png' WHERE `id_producto`=60;

SELECT id_producto, nombre, imagen FROM `productos` ORDER BY id_producto;
